import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBZqIGoPX
DhnSqe0jc90sMSAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIC6pwDItYeNqmXld
3iqDyvDnpxJiSL500w3aqg9vD1fLAAAAkIIUoH5aL0lxAlIWH//obikDot/ypX/X3j/aii
2u9v3lP/RKBwbRGXSlMkP7IOnkX/2HW1+iRhZvO2dE18YogP8+jnUCETsmVcBP8kBZvdJQ
UUh36JdIuosVCnjcF6Y55cQNBInZTPeHt3x4o71FWjoeSU3VZ8hAo10/7SNRXBIsL/yJv1
MUJx7ZGymDzZiC9g==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
